version: '3.8'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  kafka:
    image: 'confluentinc/cp-kafka:latest'
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  trino:
    image: trinodb/trino:latest
    container_name: trino
    ports:
      - "8080:8080"
    volumes:
      - trino-config:/etc/trino
      - trino-logs:/var/log/trino
    environment:
      - TRINO_LOG_LEVEL=DEBUG

  spark:
    image: bitnami/spark:latest
    ports:
      - "4040:4040"
    environment:
      SPARK_MODE: master

  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  producer:
    build: ./producer
    container_name: producer
    depends_on:
      - kafka
      - trino
      - mongodb
    environment:
      MONGO_URI: mongodb://mongo:27017
    #command: python consumer.py  
    

  spark-streaming:
    build: ./spark-streaming
    container_name: sparkS
    depends_on:
      - kafka
      - spark
      - mongodb

volumes:
  trino-config:
  trino-logs:
  mongo-data:
