version: '3.8'

services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181  
    networks:
      - trino-kafka-spark-network

  kafka:
    image: 'confluentinc/cp-kafka:latest'
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - trino-kafka-spark-network

  mongodb:
    image: mongo:4.2
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - trino-kafka-spark-network

  trino:
    image: 'trinodb/trino:latest'
    container_name: trino
    ports:
      - "8080:8080"
    networks:
      - trino-kafka-spark-network

  spark:
    image: bitnami/spark:latest
    container_name: spark
    environment:
      - SPARK_MODE=master
    ports:
      - "8081:8081"
    networks:
      - trino-kafka-spark-network

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
    networks:
      - trino-kafka-spark-network

  producer:
    build: ./producer
    depends_on:
      - kafka
    networks:
      - trino-kafka-spark-network

  spark-streaming:
    build: ./spark-streaming
    depends_on:
      - kafka
      - spark
      - mongodb
    networks:
      - trino-kafka-spark-network

networks:
  trino-kafka-spark-network:
    driver: bridge

